---
name: Format
on:
  push:
  pull_request:
jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Format Nix Files
        run: nix develop --command make format-nix-check
