---
name: Main
on:
  push:
  pull_request:
permissions:
  contents: read
  checks: write
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
      - name: Check Nix
        run: nix develop --command make check-nix
