---
name: Main
on:
  push:
  pull_request:
permissions:
  contents: read
  checks: write
  id-token: write
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Check Nix
        run: nix develop --command make check-nix
      - name: "Publish to Flakehub"
        if: github.ref == 'refs/heads/main'
        uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "dataheld/NixPlate"
          rolling: true
          visibility: "Public"
          include-output-paths: true
