---
name: Main
on:
  push:
  pull_request:
permissions:
  contents: read
  checks: write
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
      - name: Check Nix
        run: make check-nix
